-- Add type column to distinguish topical vs geographic chapters
alter table chapters add column if not exists type text not null default 'topic'
  check (type in ('topic', 'geographic'));

-- Mark existing chapters as topical
update chapters set type = 'topic' where type = 'topic';

-- Insert 80 geographic chapters
-- Using high sort_order values so they appear after topic chapters
insert into chapters (name, description, icon, sort_order, type) values
  -- Canada
  ('AB · Calgary',       'Calgary, Alberta',          '📍', 200, 'geographic'),
  ('AB · Edmonton',      'Edmonton, Alberta',          '📍', 201, 'geographic'),
  ('BC · Vancouver',     'Vancouver, British Columbia','📍', 202, 'geographic'),
  ('ON · Ottawa',        'Ottawa, Ontario',            '📍', 203, 'geographic'),
  ('ON · Toronto',       'Toronto, Ontario',           '📍', 204, 'geographic'),
  ('QC · Montreal',      'Montreal, Quebec',           '📍', 205, 'geographic'),
  -- Northeast US
  ('CT · Hartford',      'Hartford, Connecticut',      '📍', 300, 'geographic'),
  ('CT · Stamford',      'Stamford, Connecticut',      '📍', 301, 'geographic'),
  ('DC',                 'Washington, D.C.',           '📍', 302, 'geographic'),
  ('DE · Wilmington',    'Wilmington, Delaware',       '📍', 303, 'geographic'),
  ('MA · Boston',        'Boston, Massachusetts',      '📍', 304, 'geographic'),
  ('MD · Baltimore',     'Baltimore, Maryland',        '📍', 305, 'geographic'),
  ('NJ · Morris County', 'Morris County, New Jersey',  '📍', 306, 'geographic'),
  ('NY · Albany',        'Albany, New York',           '📍', 307, 'geographic'),
  ('NY · Buffalo',       'Buffalo, New York',          '📍', 308, 'geographic'),
  ('NY · Long Island',   'Long Island, New York',      '📍', 309, 'geographic'),
  ('NY · New York City', 'New York City, New York',    '📍', 310, 'geographic'),
  ('NY · Rochester',     'Rochester, New York',        '📍', 311, 'geographic'),
  ('NY · Syracuse',      'Syracuse, New York',         '📍', 312, 'geographic'),
  ('PA · Harrisburg',    'Harrisburg, Pennsylvania',   '📍', 313, 'geographic'),
  ('PA · Philadelphia',  'Philadelphia, Pennsylvania', '📍', 314, 'geographic'),
  ('PA · Pittsburgh',    'Pittsburgh, Pennsylvania',   '📍', 315, 'geographic'),
  ('RI · Providence',    'Providence, Rhode Island',   '📍', 316, 'geographic'),
  -- Southeast US
  ('AL · Birmingham',    'Birmingham, Alabama',        '📍', 400, 'geographic'),
  ('FL · Jacksonville',  'Jacksonville, Florida',      '📍', 401, 'geographic'),
  ('FL · Orlando',       'Orlando, Florida',           '📍', 402, 'geographic'),
  ('FL · South Florida', 'South Florida',              '📍', 403, 'geographic'),
  ('FL · Tampa Bay',     'Tampa Bay, Florida',         '📍', 404, 'geographic'),
  ('GA · Atlanta',       'Atlanta, Georgia',           '📍', 405, 'geographic'),
  ('KY · Louisville',    'Louisville, Kentucky',       '📍', 406, 'geographic'),
  ('LA · Baton Rouge',   'Baton Rouge, Louisiana',     '📍', 407, 'geographic'),
  ('LA · New Orleans',   'New Orleans, Louisiana',     '📍', 408, 'geographic'),
  ('NC · Charlotte',     'Charlotte, North Carolina',  '📍', 409, 'geographic'),
  ('NC · Greensboro',    'Greensboro, North Carolina', '📍', 410, 'geographic'),
  ('NC · Raleigh',       'Raleigh, North Carolina',    '📍', 411, 'geographic'),
  ('SC · Charleston',    'Charleston, South Carolina', '📍', 412, 'geographic'),
  ('SC · Columbia',      'Columbia, South Carolina',   '📍', 413, 'geographic'),
  ('TN · Chattanooga',   'Chattanooga, Tennessee',     '📍', 414, 'geographic'),
  ('TN · Knoxville',     'Knoxville, Tennessee',       '📍', 415, 'geographic'),
  ('TN · Memphis',       'Memphis, Tennessee',         '📍', 416, 'geographic'),
  ('TN · Nashville',     'Nashville, Tennessee',       '📍', 417, 'geographic'),
  ('VA · Richmond',      'Richmond, Virginia',         '📍', 418, 'geographic'),
  -- Midwest US
  ('IA · Des Moines',    'Des Moines, Iowa',           '📍', 500, 'geographic'),
  ('IL · Chicago',       'Chicago, Illinois',          '📍', 501, 'geographic'),
  ('IN · Indianapolis',  'Indianapolis, Indiana',      '📍', 502, 'geographic'),
  ('KS · Wichita',       'Wichita, Kansas',            '📍', 503, 'geographic'),
  ('MI · Detroit',       'Detroit, Michigan',          '📍', 504, 'geographic'),
  ('MI · Grand Rapids',  'Grand Rapids, Michigan',     '📍', 505, 'geographic'),
  ('MN · Twin Cities',   'Twin Cities, Minnesota',     '📍', 506, 'geographic'),
  ('MO · Kansas City',   'Kansas City, Missouri',      '📍', 507, 'geographic'),
  ('MO · Saint Louis',   'Saint Louis, Missouri',      '📍', 508, 'geographic'),
  ('NE · Omaha',         'Omaha, Nebraska',            '📍', 509, 'geographic'),
  ('OH · Cincinnati',    'Cincinnati, Ohio',           '📍', 510, 'geographic'),
  ('OH · Columbus',      'Columbus, Ohio',             '📍', 511, 'geographic'),
  ('OH · Northeast Ohio','Northeast Ohio',             '📍', 512, 'geographic'),
  ('OH · Toledo',        'Toledo, Ohio',               '📍', 513, 'geographic'),
  ('OK · Oklahoma City', 'Oklahoma City, Oklahoma',    '📍', 514, 'geographic'),
  ('OK · Tulsa',         'Tulsa, Oklahoma',            '📍', 515, 'geographic'),
  ('WI · Green Bay',     'Green Bay, Wisconsin',       '📍', 516, 'geographic'),
  ('WI · Madison',       'Madison, Wisconsin',         '📍', 517, 'geographic'),
  ('WI · Milwaukee',     'Milwaukee, Wisconsin',       '📍', 518, 'geographic'),
  -- South & Southwest US
  ('AR · Little Rock',   'Little Rock, Arkansas',      '📍', 600, 'geographic'),
  ('TX · Austin',        'Austin, Texas',              '📍', 601, 'geographic'),
  ('TX · Dallas',        'Dallas, Texas',              '📍', 602, 'geographic'),
  ('TX · Fort Worth',    'Fort Worth, Texas',          '📍', 603, 'geographic'),
  ('TX · Houston',       'Houston, Texas',             '📍', 604, 'geographic'),
  ('TX · San Antonio',   'San Antonio, Texas',         '📍', 605, 'geographic'),
  -- West US
  ('AZ · Phoenix',       'Phoenix, Arizona',           '📍', 700, 'geographic'),
  ('CA · Los Angeles',   'Los Angeles, California',    '📍', 701, 'geographic'),
  ('CA · OC',            'Orange County, California',  '📍', 702, 'geographic'),
  ('CA · Sacramento',    'Sacramento, California',     '📍', 703, 'geographic'),
  ('CA · San Diego',     'San Diego, California',      '📍', 704, 'geographic'),
  ('CA · San Francisco', 'San Francisco, California',  '📍', 705, 'geographic'),
  ('CA · Silicon Valley','Silicon Valley, California', '📍', 706, 'geographic'),
  ('CO · Denver',        'Denver, Colorado',           '📍', 707, 'geographic'),
  ('ID · Boise',         'Boise, Idaho',               '📍', 708, 'geographic'),
  ('NV · Las Vegas',     'Las Vegas, Nevada',          '📍', 709, 'geographic'),
  ('OR · Portland',      'Portland, Oregon',           '📍', 710, 'geographic'),
  ('UT · Salt Lake City','Salt Lake City, Utah',       '📍', 711, 'geographic'),
  ('WA · Seattle',       'Seattle, Washington',        '📍', 712, 'geographic'),
  -- Worldwide
  ('International',      'International members',      '🌍', 800, 'geographic'),
  ('National',           'National community',         '🇺🇸', 801, 'geographic');
