-- Add type column to distinguish topical vs geographic chapters
alter table chapters add column if not exists type text not null default 'topic'
  check (type in ('topic', 'geographic'));

-- Mark existing chapters as topical
update chapters set type = 'topic' where type = 'topic';

-- Insert 80 geographic chapters (slug = url-friendly version of name)
insert into chapters (name, slug, description, icon, sort_order, type) values
  -- Canada
  ('AB · Calgary',       'ab-calgary',        'Calgary, Alberta',          '📍', 200, 'geographic'),
  ('AB · Edmonton',      'ab-edmonton',       'Edmonton, Alberta',         '📍', 201, 'geographic'),
  ('BC · Vancouver',     'bc-vancouver',      'Vancouver, British Columbia','📍', 202, 'geographic'),
  ('ON · Ottawa',        'on-ottawa',         'Ottawa, Ontario',           '📍', 203, 'geographic'),
  ('ON · Toronto',       'on-toronto',        'Toronto, Ontario',          '📍', 204, 'geographic'),
  ('QC · Montreal',      'qc-montreal',       'Montreal, Quebec',          '📍', 205, 'geographic'),
  -- Northeast US
  ('CT · Hartford',      'ct-hartford',       'Hartford, Connecticut',      '📍', 300, 'geographic'),
  ('CT · Stamford',      'ct-stamford',       'Stamford, Connecticut',      '📍', 301, 'geographic'),
  ('DC',                 'dc',                'Washington, D.C.',           '📍', 302, 'geographic'),
  ('DE · Wilmington',    'de-wilmington',     'Wilmington, Delaware',       '📍', 303, 'geographic'),
  ('MA · Boston',        'ma-boston',         'Boston, Massachusetts',      '📍', 304, 'geographic'),
  ('MD · Baltimore',     'md-baltimore',      'Baltimore, Maryland',        '📍', 305, 'geographic'),
  ('NJ · Morris County', 'nj-morris-county',  'Morris County, New Jersey',  '📍', 306, 'geographic'),
  ('NY · Albany',        'ny-albany',         'Albany, New York',           '📍', 307, 'geographic'),
  ('NY · Buffalo',       'ny-buffalo',        'Buffalo, New York',          '📍', 308, 'geographic'),
  ('NY · Long Island',   'ny-long-island',    'Long Island, New York',      '📍', 309, 'geographic'),
  ('NY · New York City', 'ny-new-york-city',  'New York City, New York',    '📍', 310, 'geographic'),
  ('NY · Rochester',     'ny-rochester',      'Rochester, New York',        '📍', 311, 'geographic'),
  ('NY · Syracuse',      'ny-syracuse',       'Syracuse, New York',         '📍', 312, 'geographic'),
  ('PA · Harrisburg',    'pa-harrisburg',     'Harrisburg, Pennsylvania',   '📍', 313, 'geographic'),
  ('PA · Philadelphia',  'pa-philadelphia',   'Philadelphia, Pennsylvania', '📍', 314, 'geographic'),
  ('PA · Pittsburgh',    'pa-pittsburgh',     'Pittsburgh, Pennsylvania',   '📍', 315, 'geographic'),
  ('RI · Providence',    'ri-providence',     'Providence, Rhode Island',   '📍', 316, 'geographic'),
  -- Southeast US
  ('AL · Birmingham',    'al-birmingham',     'Birmingham, Alabama',        '📍', 400, 'geographic'),
  ('FL · Jacksonville',  'fl-jacksonville',   'Jacksonville, Florida',      '📍', 401, 'geographic'),
  ('FL · Orlando',       'fl-orlando',        'Orlando, Florida',           '📍', 402, 'geographic'),
  ('FL · South Florida', 'fl-south-florida',  'South Florida',              '📍', 403, 'geographic'),
  ('FL · Tampa Bay',     'fl-tampa-bay',      'Tampa Bay, Florida',         '📍', 404, 'geographic'),
  ('GA · Atlanta',       'ga-atlanta',        'Atlanta, Georgia',           '📍', 405, 'geographic'),
  ('KY · Louisville',    'ky-louisville',     'Louisville, Kentucky',       '📍', 406, 'geographic'),
  ('LA · Baton Rouge',   'la-baton-rouge',    'Baton Rouge, Louisiana',     '📍', 407, 'geographic'),
  ('LA · New Orleans',   'la-new-orleans',    'New Orleans, Louisiana',     '📍', 408, 'geographic'),
  ('NC · Charlotte',     'nc-charlotte',      'Charlotte, North Carolina',  '📍', 409, 'geographic'),
  ('NC · Greensboro',    'nc-greensboro',     'Greensboro, North Carolina', '📍', 410, 'geographic'),
  ('NC · Raleigh',       'nc-raleigh',        'Raleigh, North Carolina',    '📍', 411, 'geographic'),
  ('SC · Charleston',    'sc-charleston',     'Charleston, South Carolina', '📍', 412, 'geographic'),
  ('SC · Columbia',      'sc-columbia',       'Columbia, South Carolina',   '📍', 413, 'geographic'),
  ('TN · Chattanooga',   'tn-chattanooga',    'Chattanooga, Tennessee',     '📍', 414, 'geographic'),
  ('TN · Knoxville',     'tn-knoxville',      'Knoxville, Tennessee',       '📍', 415, 'geographic'),
  ('TN · Memphis',       'tn-memphis',        'Memphis, Tennessee',         '📍', 416, 'geographic'),
  ('TN · Nashville',     'tn-nashville',      'Nashville, Tennessee',       '📍', 417, 'geographic'),
  ('VA · Richmond',      'va-richmond',       'Richmond, Virginia',         '📍', 418, 'geographic'),
  -- Midwest US
  ('IA · Des Moines',    'ia-des-moines',     'Des Moines, Iowa',           '📍', 500, 'geographic'),
  ('IL · Chicago',       'il-chicago',        'Chicago, Illinois',          '📍', 501, 'geographic'),
  ('IN · Indianapolis',  'in-indianapolis',   'Indianapolis, Indiana',      '📍', 502, 'geographic'),
  ('KS · Wichita',       'ks-wichita',        'Wichita, Kansas',            '📍', 503, 'geographic'),
  ('MI · Detroit',       'mi-detroit',        'Detroit, Michigan',          '📍', 504, 'geographic'),
  ('MI · Grand Rapids',  'mi-grand-rapids',   'Grand Rapids, Michigan',     '📍', 505, 'geographic'),
  ('MN · Twin Cities',   'mn-twin-cities',    'Twin Cities, Minnesota',     '📍', 506, 'geographic'),
  ('MO · Kansas City',   'mo-kansas-city',    'Kansas City, Missouri',      '📍', 507, 'geographic'),
  ('MO · Saint Louis',   'mo-saint-louis',    'Saint Louis, Missouri',      '📍', 508, 'geographic'),
  ('NE · Omaha',         'ne-omaha',          'Omaha, Nebraska',            '📍', 509, 'geographic'),
  ('OH · Cincinnati',    'oh-cincinnati',     'Cincinnati, Ohio',           '📍', 510, 'geographic'),
  ('OH · Columbus',      'oh-columbus',       'Columbus, Ohio',             '📍', 511, 'geographic'),
  ('OH · Northeast Ohio','oh-northeast-ohio', 'Northeast Ohio',             '📍', 512, 'geographic'),
  ('OH · Toledo',        'oh-toledo',         'Toledo, Ohio',               '📍', 513, 'geographic'),
  ('OK · Oklahoma City', 'ok-oklahoma-city',  'Oklahoma City, Oklahoma',    '📍', 514, 'geographic'),
  ('OK · Tulsa',         'ok-tulsa',          'Tulsa, Oklahoma',            '📍', 515, 'geographic'),
  ('WI · Green Bay',     'wi-green-bay',      'Green Bay, Wisconsin',       '📍', 516, 'geographic'),
  ('WI · Madison',       'wi-madison',        'Madison, Wisconsin',         '📍', 517, 'geographic'),
  ('WI · Milwaukee',     'wi-milwaukee',      'Milwaukee, Wisconsin',       '📍', 518, 'geographic'),
  -- South & Southwest US
  ('AR · Little Rock',   'ar-little-rock',    'Little Rock, Arkansas',      '📍', 600, 'geographic'),
  ('TX · Austin',        'tx-austin',         'Austin, Texas',              '📍', 601, 'geographic'),
  ('TX · Dallas',        'tx-dallas',         'Dallas, Texas',              '📍', 602, 'geographic'),
  ('TX · Fort Worth',    'tx-fort-worth',     'Fort Worth, Texas',          '📍', 603, 'geographic'),
  ('TX · Houston',       'tx-houston',        'Houston, Texas',             '📍', 604, 'geographic'),
  ('TX · San Antonio',   'tx-san-antonio',    'San Antonio, Texas',         '📍', 605, 'geographic'),
  -- West US
  ('AZ · Phoenix',       'az-phoenix',        'Phoenix, Arizona',           '📍', 700, 'geographic'),
  ('CA · Los Angeles',   'ca-los-angeles',    'Los Angeles, California',    '📍', 701, 'geographic'),
  ('CA · OC',            'ca-oc',             'Orange County, California',  '📍', 702, 'geographic'),
  ('CA · Sacramento',    'ca-sacramento',     'Sacramento, California',     '📍', 703, 'geographic'),
  ('CA · San Diego',     'ca-san-diego',      'San Diego, California',      '📍', 704, 'geographic'),
  ('CA · San Francisco', 'ca-san-francisco',  'San Francisco, California',  '📍', 705, 'geographic'),
  ('CA · Silicon Valley','ca-silicon-valley', 'Silicon Valley, California', '📍', 706, 'geographic'),
  ('CO · Denver',        'co-denver',         'Denver, Colorado',           '📍', 707, 'geographic'),
  ('ID · Boise',         'id-boise',          'Boise, Idaho',               '📍', 708, 'geographic'),
  ('NV · Las Vegas',     'nv-las-vegas',      'Las Vegas, Nevada',          '📍', 709, 'geographic'),
  ('OR · Portland',      'or-portland',       'Portland, Oregon',           '📍', 710, 'geographic'),
  ('UT · Salt Lake City','ut-salt-lake-city', 'Salt Lake City, Utah',       '📍', 711, 'geographic'),
  ('WA · Seattle',       'wa-seattle',        'Seattle, Washington',        '📍', 712, 'geographic'),
  -- Worldwide
  ('International',      'international',     'International members',      '🌍', 800, 'geographic'),
  ('National',           'national',          'National community',         '🇺🇸', 801, 'geographic');
